const STORE_URLS: Record<string, string> = {
  // Fast food & dining
  "mcdonald's": "https://www.mcdonalds.com",
  "mcdonalds": "https://www.mcdonalds.com",
  "subway": "https://www.subway.com",
  "domino's": "https://www.dominos.com",
  "dominos": "https://www.dominos.com",
  "taco bell": "https://www.tacobell.com",
  "tacobell": "https://www.tacobell.com",
  "sonic": "https://www.sonicdrivein.com",
  "sonic drive-in": "https://www.sonicdrivein.com",
  "wendy's": "https://www.wendys.com",
  "wendys": "https://www.wendys.com",
  "burger king": "https://www.bk.com",
  "burgerking": "https://www.bk.com",
  "pizza hut": "https://www.pizzahut.com",
  "pizzahut": "https://www.pizzahut.com",
  "kfc": "https://www.kfc.com",
  "kentucky fried chicken": "https://www.kfc.com",
  "chick-fil-a": "https://www.chick-fil-a.com",
  "chick fil a": "https://www.chick-fil-a.com",
  "chickfila": "https://www.chick-fil-a.com",
  "popeyes": "https://www.popeyes.com",
  "panda express": "https://www.pandaexpress.com",
  "pandaexpress": "https://www.pandaexpress.com",
  "little caesars": "https://www.littlecaesars.com",
  "little caesar's": "https://www.littlecaesars.com",
  "papa john's": "https://www.papajohns.com",
  "papa johns": "https://www.papajohns.com",
  "arby's": "https://www.arbys.com",
  "arbys": "https://www.arbys.com",
  "jimmy john's": "https://www.jimmyjohns.com",
  "jimmy johns": "https://www.jimmyjohns.com",
  "dairy queen": "https://www.dairyqueen.com",
  "dairyqueen": "https://www.dairyqueen.com",
  "hardee's": "https://www.hardees.com",
  "hardees": "https://www.hardees.com",
  "jack in the box": "https://www.jackinthebox.com",
  "whataburger": "https://www.whataburger.com",
  "five guys": "https://www.fiveguys.com",
  "fiveguys": "https://www.fiveguys.com",
  "denny's": "https://www.dennys.com",
  "dennys": "https://www.dennys.com",
  "ihop": "https://www.ihop.com",
  "applebee's": "https://www.applebees.com",
  "applebees": "https://www.applebees.com",
  "olive garden": "https://www.olivegarden.com",
  "outback steakhouse": "https://www.outback.com",
  "outback": "https://www.outback.com",
  "red lobster": "https://www.redlobster.com",
  "chili's": "https://www.chilis.com",
  "chilis": "https://www.chilis.com",
  "texas roadhouse": "https://www.texasroadhouse.com",
  "panera": "https://www.panerabread.com",
  "panera bread": "https://www.panerabread.com",
  "chipotle": "https://www.chipotle.com",
  "starbucks": "https://www.starbucks.com",
  "dunkin'": "https://www.dunkindonuts.com",
  "dunkin": "https://www.dunkindonuts.com",
  "dunkin donuts": "https://www.dunkindonuts.com",
  "cracker barrel": "https://www.crackerbarrel.com",

  // Retail & shopping
  "walmart": "https://www.walmart.com",
  "target": "https://www.target.com",
  "amazon": "https://www.amazon.com",
  "costco": "https://www.costco.com",
  "best buy": "https://www.bestbuy.com",
  "bestbuy": "https://www.bestbuy.com",
  "kohl's": "https://www.kohls.com",
  "kohls": "https://www.kohls.com",
  "macy's": "https://www.macys.com",
  "macys": "https://www.macys.com",
  "nordstrom": "https://www.nordstrom.com",
  "gap": "https://www.gap.com",
  "old navy": "https://www.oldnavy.com",
  "banana republic": "https://www.bananarepublic.com",
  "j.crew": "https://www.jcrew.com",
  "forever 21": "https://www.forever21.com",
  "h&m": "https://www.hm.com",
  "zara": "https://www.zara.com",
  "express": "https://www.express.com",
  "american eagle": "https://www.ae.com",
  "abercrombie": "https://www.abercrombie.com",
  "hollister": "https://www.hollisterco.com",
  "victoria's secret": "https://www.victoriassecret.com",
  "bath & body works": "https://www.bathandbodyworks.com",
  "dollar general": "https://www.dollargeneral.com",
  "dollar tree": "https://www.dollartree.com",
  "family dollar": "https://www.familydollar.com",
  "ross": "https://www.rossstores.com",
  "tj maxx": "https://www.tjmaxx.com",
  "marshalls": "https://www.marshalls.com",
  "home depot": "https://www.homedepot.com",
  "homedepot": "https://www.homedepot.com",
  "lowe's": "https://www.lowes.com",
  "lowes": "https://www.lowes.com",
  "ikea": "https://www.ikea.com",
  "wayfair": "https://www.wayfair.com",
  "overstock": "https://www.overstock.com",
  "bed bath & beyond": "https://www.bedbathandbeyond.com",
  "williams-sonoma": "https://www.williams-sonoma.com",
  "crate and barrel": "https://www.crateandbarrel.com",
  "pottery barn": "https://www.potterybarn.com",
  "sephora": "https://www.sephora.com",
  "ulta": "https://www.ulta.com",
  "ulta beauty": "https://www.ulta.com",

  // Health & pharmacy
  "walgreens": "https://www.walgreens.com",
  "cvs": "https://www.cvs.com",
  "cvs pharmacy": "https://www.cvs.com",
  "rite aid": "https://www.riteaid.com",
  "gnc": "https://www.gnc.com",
  "vitamin shoppe": "https://www.vitaminshoppe.com",

  // Automotive
  "autozone": "https://www.autozone.com",
  "o'reilly auto parts": "https://www.oreillyauto.com",
  "o'reilly": "https://www.oreillyauto.com",
  "oreilly": "https://www.oreillyauto.com",
  "jiffy lube": "https://www.jiffylube.com",
  "valvoline": "https://www.valvoline.com",
  "pep boys": "https://www.pepboys.com",
  "firestone": "https://www.firestonecompleteautocare.com",
  "midas": "https://www.midas.com",
  "advance auto parts": "https://www.advanceautoparts.com",
  "advance auto": "https://www.advanceautoparts.com",
  "napa auto parts": "https://www.napaonline.com",
  "napa": "https://www.napaonline.com",

  // Entertainment
  "amc theatres": "https://www.amctheatres.com",
  "amc": "https://www.amctheatres.com",
  "regal cinemas": "https://www.regmovies.com",
  "regal": "https://www.regmovies.com",
  "cinemark": "https://www.cinemark.com",
  "fandango": "https://www.fandango.com",
  "ticketmaster": "https://www.ticketmaster.com",
  "stubhub": "https://www.stubhub.com",
  "disney": "https://www.disney.com",
  "netflix": "https://www.netflix.com",
  "hulu": "https://www.hulu.com",
  "spotify": "https://www.spotify.com",
  "steam": "https://store.steampowered.com",

  // Travel
  "expedia": "https://www.expedia.com",
  "hotels.com": "https://www.hotels.com",
  "hotwire": "https://www.hotwire.com",
  "priceline": "https://www.priceline.com",
  "kayak": "https://www.kayak.com",
  "booking.com": "https://www.booking.com",
  "airbnb": "https://www.airbnb.com",
  "united airlines": "https://www.united.com",
  "delta": "https://www.delta.com",
  "southwest": "https://www.southwest.com",
  "southwest airlines": "https://www.southwest.com",
  "american airlines": "https://www.aa.com",
  "jetblue": "https://www.jetblue.com",
  "spirit airlines": "https://www.spirit.com",
  "marriott": "https://www.marriott.com",
  "hilton": "https://www.hilton.com",
  "hyatt": "https://www.hyatt.com",

  // Tech & software
  "godaddy": "https://www.godaddy.com",
  "hostgator": "https://www.hostgator.com",
  "bluehost": "https://www.bluehost.com",
  "namecheap": "https://www.namecheap.com",
  "siteground": "https://www.siteground.com",
  "hostinger": "https://www.hostinger.com",
  "wix": "https://www.wix.com",
  "squarespace": "https://www.squarespace.com",
  "shopify": "https://www.shopify.com",
  "norton": "https://us.norton.com",
  "mcafee": "https://www.mcafee.com",
  "bitdefender": "https://www.bitdefender.com",
  "malwarebytes": "https://www.malwarebytes.com",
  "avg": "https://www.avg.com",
  "avast": "https://www.avast.com",
  "acronis": "https://www.acronis.com",
  "ashampoo": "https://www.ashampoo.com",
  "hola vpn": "https://hola.org",
  "spytech": "https://www.spytech-web.com",

  // Pets
  "petco": "https://www.petco.com",
  "petsmart": "https://www.petsmart.com",

  // Flowers & gifts
  "1-800-flowers": "https://www.1800flowers.com",
  "1800flowers": "https://www.1800flowers.com",
  "ftd": "https://www.ftd.com",
  "proflowers": "https://www.proflowers.com",
};

export function getStoreUrl(storeName: string): string | null {
  if (!storeName) return null;
  const key = storeName.toLowerCase().trim();
  if (STORE_URLS[key]) return STORE_URLS[key];
  // Try partial match — strip common suffixes like "coupons", "deals"
  const stripped = key
    .replace(/\s+(coupons?|deals?|promo|offers?)$/i, "")
    .trim();
  if (STORE_URLS[stripped]) return STORE_URLS[stripped];
  // Try prefix match for longer store names
  for (const [brand, url] of Object.entries(STORE_URLS)) {
    if (stripped.startsWith(brand) || brand.startsWith(stripped)) return url;
  }
  return null;
}
